// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY0q1B-g7sz2kyX-h7DzTTjPTzOv9_QHM',
    appId: '1:367055904950:web:442e41f6127cbc45470617',
    messagingSenderId: '367055904950',
    projectId: 'pulse-vpn-app-46893',
    authDomain: 'pulse-vpn-app-46893.firebaseapp.com',
    storageBucket: 'pulse-vpn-app-46893.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWqaqSkBUg_JLU-5poVk2W_wwYJNHdqM8',
    appId: '1:367055904950:android:caa2886f7d00beb2470617',
    messagingSenderId: '367055904950',
    projectId: 'pulse-vpn-app-46893',
    storageBucket: 'pulse-vpn-app-46893.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF4skPLH0pY9o3NfAe8YIqjw3MVpQsu_M',
    appId: '1:367055904950:ios:aedb9fbd0e8c5bc8470617',
    messagingSenderId: '367055904950',
    projectId: 'pulse-vpn-app-46893',
    storageBucket: 'pulse-vpn-app-46893.firebasestorage.app',
    androidClientId: '367055904950-q32q5be0so3ar1b0f9e990l56qe2u92s.apps.googleusercontent.com',
    iosClientId: '367055904950-s8gfs7vfnf32qeo4dvm9ce3qb89k11a5.apps.googleusercontent.com',
    iosBundleId: 'com.example.vpnmac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF4skPLH0pY9o3NfAe8YIqjw3MVpQsu_M',
    appId: '1:367055904950:ios:aedb9fbd0e8c5bc8470617',
    messagingSenderId: '367055904950',
    projectId: 'pulse-vpn-app-46893',
    storageBucket: 'pulse-vpn-app-46893.firebasestorage.app',
    androidClientId: '367055904950-q32q5be0so3ar1b0f9e990l56qe2u92s.apps.googleusercontent.com',
    iosClientId: '367055904950-s8gfs7vfnf32qeo4dvm9ce3qb89k11a5.apps.googleusercontent.com',
    iosBundleId: 'com.example.vpnmac',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY0q1B-g7sz2kyX-h7DzTTjPTzOv9_QHM',
    appId: '1:367055904950:web:344532869ab4ee97470617',
    messagingSenderId: '367055904950',
    projectId: 'pulse-vpn-app-46893',
    authDomain: 'pulse-vpn-app-46893.firebaseapp.com',
    storageBucket: 'pulse-vpn-app-46893.firebasestorage.app',
  );
}
